apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location /api/ {
            rewrite ^/api(/.*)$ $1 break;  
            proxy_pass http://springboot-backend-service:8080;
        }

        location / {
            proxy_pass http://react-frontend-service:80;
        }
    }