apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok-container
          image: ngrok/ngrok:latest
          # Запуск Ngrok с логами отладки для вывода URL туннеля
          command: ["/bin/sh", "-c", "ngrok http nginx-service:80 --log stdout --log-level debug"]
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: NGROK_AUTHTOKEN
          ports:
            - containerPort: 4040  # Порт для API Ngrok