apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hahaloh-front
  namespace: flux-system
spec:
  image: balalaika7771/hahaloh-front
  interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hahaloh-back
  namespace: flux-system
spec:
  image: balalaika7771/hahaloh-back
  interval: 1m
