apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: image-update
  namespace: flux-system
spec:
  interval: 1m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@yourdomain.com
        name: FluxCD Bot
      messageTemplate: 'Update images in {{ .AutomationObject.metadata.name }}'
    push:
      branch: main
  update:
    path: ./clusters/my-cluster
