apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;

        # Маршрутизация на бэкенд для запросов, начинающихся с /api/
        location /api/ {
            proxy_pass http://springboot-backend-service:8080;
        }

        # Все остальные запросы направляются на фронтенд
        location / {
            proxy_pass http://react-frontend-service:80;
        }
    }